
const inventory = [
    'AirPods with Charging Case',
    'AirPods with Wireless Charging Case',
    'AirPods Pro with Wireless Charging Case',
    'AirPods Pro with Magsafe Charging Case',
    'AirPods (3rd Gen)',
    'AirPods Max w/ Smart Case',
    'Wireless Charging Case for AirPods',
    'EarPods with Lightning Connector',
    'EarPods with 3.5mm',
    'USB-C to 3.5mm Headphone Jack',
    'Lightning to 3.5mm Headphone Jack',
    'USB-C to VGA',
    'Thunderbolt 3 (USB-C) to Thunderbolt 2',
    'USB-C to SD',
    'USB-C To Digital AV',
    'USB-C to MagSafe 3',
    'USB-C Charge Cable (1m)',
    'USB-C Charge Cable (2m)',
    'DNR USB-C to Lightning (1m)',
    'USB-C to Lightning (1m)',
    'USB-C to Lightning (2m)',
    'Lightning to USB (1m)',
    'Lightning to USB (2m)',
    '5W Power Adaper',
    '12W Power Adapter',
    '20W Power Adapter',
    'MagSafe Charger',
    'Thundebolt 3 (USB-C)',
    'MagSafe Duo Charger',
    'Magnetic Charging Dock',
    'Magnetic Charging to USB',
    'Magnetic Fast Charging to USB-C',
    '45W MagSafe 2 Power Adapter',
    '60W MagSafe 2 Power Adapter',
    '85W MagSafe 2 Power Adapter',
    '45W MagSafe Power Adapter',
    '60W MagSafe Power Adapter',
    '85W MagSafe Power Adapter',
    '30W Power Adapter USB-C',
    '61W Power Adapter USC-C',
    '67W Power Adapter USB-C',
    '96W Power Adapter USB-C',
    'Magic Trackpad',
    'Magic Mouse',
    'Magic Keyboard Black for 11" iPad',
    'Magic Keyboard White for 11" iPad',
    'Smart Keyboard Folio Black ',
    'DNR Magic Keyboard',
    'Smart Keyboard',
    'Magic Keyboard',
    'Magic Keyboard w/ Number Pad',
    'World Travel Adapter KIt',
    'Power Adapter Extension Cable',
    'Magic Keyboard Black for 12.9" iPad',
    'Magic Keyboard White for 12.9" iPad',
    'Smart Keyboard Folio Black for 12.9" iPad',
    'Apple Pencil ',
    'Apple Pencil 2nd Gen',
    'Apple Pencil Tips',
    'iPad mini Smart Cover Black',
    'iPad mini Smart Cover Pink',
    'iPad Smart Cover 9.7" Blue',
    'iPad Smart Cover 9.7" Pink',
    'iPad Smar Cover Pink',
    'Thunderbolt to FireWire Adapter ',
    'Lightning to Digital AV',
    'USB-C to USB Adapter',
    'MagSafe to MagSafe 2 Converter',
    '30-pin to USB Cable',
    'Lightning to USB 3 Camera Adapter',
    'Lightning to VGA Adapter',
    'AirTag (1 pack)',
    'AirTag (4 pack)',
    'HomePod Mini (Yellow)',
    'HomePod Mini (Blue)',
    'HomePod Mini (Orange)',
    'HomePod Mini (White)',
    'HomePod Mini (Space Gray)',
    'Apple TV HD 32GB',
    'Apple TV 4K HDR 32GB',
    'Apple TV 4K HDR 64GB',
    'Apple Watch Series 3 GPS 42mm/Case Silver Aluminum Sport Band White',
    'Apple Watch SE GPS 44mm/Case Silver Aluminum Sport Band Abyss Blue ',
    'Apple Watch SE GPS 44mm/Case Gold Aluminum Sport Band Starlight',
    'Apple Watch SE GPS 44mm/Case Space Gray Aluminum Sport Band Midnight',
    'Apple Watch Series 7 GPS 41mm/Case Green Aluminum Sport Band Clover',
    'Apple Watch Series 7 GPS 45mm/Case Green Aluminum Sport Band Clover',
    'Apple Watch Series 7 GPS 41mm/Case Blue Aluminum Sport Band Blue Abyss',
    'Apple Watch Series 7 GPS 45mm/Case Blue Aluminum Sport Band Blue Abyss',
    'Apple Watch Series 7 GPS 41mm/Case Midnight Aluminum Sport Midnight',
    'Apple Watch Series 7 GPS 45mm/Case Midnight Aluminum Sport Band Midnight',
    'Apple Watch Series 7 GPS 41mm/Case Starlight Aluminum Sport Band Starlight',
    'Apple Watch Series 7 GPS 45mm/Case Starlight Aluminum Sport Band Starlight',
    'Apple Watch Series 7 GPS 41mm/Case (PRODUCT) Red Aluminum Sport Band Red',
    'Apple Watch Series 7 GPS 45mm/Case (PRODUCT) Red Aluminum Sport Band Red',
    'Mac Mini M1/8GB/256GB Silver',
    'Mac Mini i5/8GB/512GB Space Gray',
    'Mac Mini M1/8GB/512GB Silver',
    'iPad Mini (6th Gen) 64GB Wi-FI Pink',
    'iPad Mini (6th Gen) 256GB Wi-FI Pink',
    'iPad Mini (6th Gen) 64GB Wi-FI Starlight',
    'iPad Mini (6th Gen) 256GB Wi-FI Starlight',
    'iPad Mini (6th Gen) 64GB Wi-FI Purple',
    'iPad Mini (6th Gen) 256GB Wi-FI Purple',
    'iPad Mini (6th Gen) 64GB Wi-FI Space Gray',
    'iPad Mini (6th Gen) 256GB Wi-FI Space Gray',
    'iPad (9th Gen) 64GB Wi-F Silver',
    'iPad (9th Gen) 256GB Wi-Fi Space Gray',
    'iPad Air (4th Gen) 64GB Sky Blue Wi-Fi+Cellualr',
    'iPad Air (4th Gen) 64GB Sky Blue Wi-Fi',
    'iPad Air (4th Gen) 256GB Sky Blue Wi-Fi',
    'iPad Air (4th Gen) 64GB Green Wi-Fi',
    'iPad Air (4th Gen) 256GB Sky Blue Wi-Fi',
    'iPad Air (4th Gen) 64GB Space Gray Wi-Fi',
    'iPad Air (4th Gen) 256GB Space Gray Wi-Fi',
    'iPad Air (4th Gen) 64GB Rose Gold Wi-Fi',
    'iPad Air (4th Gen) 256GB Rose Gold Wi-Fi',
    'iPad Air (4th Gen) 64GB Silver Wi-Fi',
    'iPad Air (4th Gen) 256GB Silver Wi-Fi',
    'iPad Pro 11" Wi-Fi 128GB Space Gray',
    'iPad Pro 11" Wi-Fi 256GB Space Gray',
    'iPad Pro 11" Wi-Fi 512GB Space Gray',
    'iPad Pro 11" Wi-Fi 1TB Space Gray',
    'iPad Pro 11" Wi-Fi 128GB Silver',
    'iPad Pro 11" Wi-Fi 256GB Silver',
    'iPad Pro 11" Wi-Fi 512GB Silver',
    'iPad Pro 11" Wi-Fi 1TB Silver',
    'iPad Pro 12" Wi-Fi 128GB Space Gray',
    'iPad Pro 12" Wi-Fi 256GB Space Gray',
    'iPad Pro 12" Wi-Fi 512GB Space Gray',
    'iPad Pro 12" Wi-Fi 1TB Space Gray',
    'iPad Pro 12" Wi-Fi 128GB Silver',
    'iPad Pro 12" Wi-Fi 256GB Silver',
    'iPad Pro 12" Wi-Fi 512GB Silver',
    'iPad Pro 12" Wi-Fi 1TB Silver',
    'MacBook Air M1/8GB/256 Space Gray',
    'MacBook Air M1/8GB/256 Silver',
    'MacBook Air M1/8GB/256 Gold',
    'MacBook Air M1/8GB/512GB Space Gray',
    'MacBook Air M1/8GB/512GB Silver',
    'MacBook Air M1/8GB/512GB Gold',
    'MacBook Pro 13" M1/8GB/256GB Space Gray',
    'MacBook Pro 13" M1/8GB/512GB Space Gray',
    'MacBook Pro 13" M1/8GB/512GB Silver',
    'Custom MBP 13 8C 8C 256GB SG',
    'MacBook Pro 14" M1/16GB/512GB Space Gray',
    'MacBook Pro 14" M1/16GB/1TB Silver',
    'MacBook Pro 14" M1/16GB/1TB Space Gray',
    'MacBook Pro 14" M1/16GB/512GB Silver',
    '(CUSTOM) MacBook Pro 14" M1 Pro 16GB/512GB Space Gray',
    'DNR MacBook Pro 16" 2.3GHz i9/16GB/1TB Silver',
    'DNR MacBook Pro 16" 2.3GHz i9/16GB/1TB Space Gray ',
    'MacBook Pro 16" M1 Pro/16GB/512GB Space Gray',
    'MacBook Pro 16" M1 Pro/16GB/512GB Silver',
    'MacBook Pro 16" M1 Pro/16GB/1TB Space Gray',
    'MacBook Pro 16" M1 Pro/16GB/1TB Silver',
    'MacBook Pro 16" M1 MAX/32GB/1TB Space Gray',
    '(CUSTOM) MacBook Pro 16" M1 MAX/32GB/1TB Space Gray',
    'MacBook Pro 16" M1 MAX/32GB/1TB Silver',
    '24" iMac 4.5K Display M1 8C 8C 256GB Blue',
    '2020 27" iMac 3.8GHz 8 core 10th Gen i7 512GB',
    '2021 27" iMac 3.3GHz 6 core 10th Gen i5 512GB',
    'Apple Watch Series 7 GPS+Cellular 45mm/Case Midnight Aluminum Sport Band Midnight',
    'Apple Watch Series 7 GPS 45mm/Case Blue Aluminum Sport Band Blue Abyss',
    'iPad Pro 11" Wi-Fi+ Cellular 2TB Space Gray',
    'Custom Mac Mini M1 8 core cpu | 8 core gpu 256GB SSD',
    '24" iMac 4.5K Display M1 8C 8C 512GB Blue',
    '24" iMac 4.5K Display M1 8C 8C Purple',
    ];

    const MPN = [
        'MV7N2AM/A',
        'MRXJ2AM/A',
        'MWP22AM/A',
        'MLWK3AM/A',
        'MME73AM/A',
        'MGYH3AM/A',
        'MR8U2AM/A',
        'MMTN2AM/A',
        'MNHF2AM/A',
        'MU7E2AM/A',
        'MMX62AM/A',
        'MJ1L2AM/A',
        'MMEL2AM/A',
        'MUFG2AM/A',
        'MUF82AM/A',
        'MLYV3AM/A',
        'MM093AM/A',
        'MLL82AM/A',
        'MX0K2AM/A',
        'MM0A3AM/A',
        'MQGH2AM/A',
        'MXLY2AM/A',
        'MD819AM/A',
        'MD810LL/A',
        'MGN03AM/A',
        'MHJA3AM/A',
        'MHXH3AM/A',
        'MQ4H2AM/A',
        'MHXF3AM/A',
        'MLDW2AM/A',
        'MX2E2AM/A',
        'MLWJ3AM/A',
        'MD592LL/A',
        'MD565LL/A',
        'MD506LL/A',
        'MC747LL/A',
        'MC461LL/A',
        'MC556LL/B',
        'MY1W2AM/A',
        'MRW22LL/A',
        'MKU63AM/A',
        'MX0J2AM/A',
        'MK2D3AM/A',
        'MK2E3AM/A',
        'MXQT2LL/A',
        'MJQJ3LL/A',
        'MXNK2LL/A',
        'MLA22LL/A',
        'MX3L2LL/A',
        'MK2A3LL/A',
        'MQ052LL/A',
        'MD837AM/A',
        'MK122LL/A',
        'MJQK3LL/A',
        'MJQL3LL/A',
        'MXNL2LL/A',
        'MK0C2AM/A',
        'MU8F2AM/A',
        'MLUN2AM/A',
        'MVQD2ZM/A',
        'MVQF2ZM/A',
        'MQ4P2ZM/A',
        'MQ4Q2ZM/A',
        'MVQ42ZM/A',
        'MD464LL/A',
        'MD826AM/A',
        'MJ1M2AM/A',
        'MD504LL/A',
       ' MA591G/C',
        'MK0W2AM/A',
        'MD825AM/A',
        'MX532AM/A',
        'MX542AM/A',
        'MJ2E3LL/A',
        'MJ2C3LL/A',
        'MJ2D3LL/A',
        'MY5H2LL/A',
        'MY5G2LL/A',
        'MHY93LL/A',
        'MXGY2LL/A',
        'MXH02LL/A',
        'MTF22LL/A',
        'MKQ43LL/A',
        'MKQ53LL/A',
        'MKQ63LL/A',
        'MKN03LL/A',
        'MKN73LL/A',
        'MKN13LL/A',
        'MKN83LL/A',
        'MKMX3LL/A',
        'MKN53LL/A',
        'MKMY3LL/A',
        'MKN63LL/A',
        'MKN93LL/A',
        'MKN23LL/A',
        'MGNR3LL/A',
        'MXNG2LL/A',
        'MGNT3LL/A',
        'MLWL3LL/A',
        'MLWR3LL/A',
        'MK7P3LL/A',
        'MK7V3LL/A',
        'MK7R3LL/A',
        'MK7X3LL/A',
        'MK7M3LL/A',
        'MK7T3LL/A',
        'MK2L3LL/A',
        'MK2N3LL/A',
        'MYJ12LL/A',
        'MYFQ2LL/A',
        'MYFY2LL/A',
        'MYFR2LL/A',
        'MYG02LL/A',
        'MYFM2LL/A',
        'MYFT2LL/A',
        'MYFP2LL/A',
        'MYFX2LL/A',
        'MYFN2LL/A',
        'MYFW2LL/A',
        'MHQR3LL/A',
        'MHQU3LL/A',
        'MHQW3LL/A',
        'MHQY3LL/A',
        'MHQT3LL/A',
        'MHQV3LL/A',
        'MHQX3LL/A',
        'MHR03LL/A',
        'MHNF3LL/A',
        'MHNH3LL/A',
        'MHNK3LL/A',
        'MHNM3LL/A',
        'MHNG3LL/A',
        'MHNJ3LL/A',
        'MHNL3LL/A',
        'MHNN3LL/A',
        'MGN63LL/A',
        'MGN93LL/A',
        'MGND3LL/A',
        'MGN73LL/A',
        'MGNA3LL/A',
        'MGNE3LL/A',
        'MYD82LL/A',
        'MYD92LL/A',
        'MYDC2LL/A',
        'Z11B',
        'MKGP3LL/A',
        'MKGT3LL/A',
        'MKGQ3LL/A',
        'MKGR3LL/A',
        'Z15G',
        'MVVM2LL/A',
        'MVVK2LL/A',
        'MK183LL/A',
        'MK1E3LL/A',
        'MK193LL/A',
        'MK1F3LL/A',
        'MK1A3LL/A',
        'Z14V',
        'MK1H3LL/A',
        'MGPK3LL/A',
        'MXWV2LL/A',
        'MXWU2LL/A',
        'MKJ73LL/A',
        'MKJA3LL/A',
        'MHN23LL/A',
        'Z12N',
        'MGPL3LL/A',
        'Z130',
    ];

    
    export {inventory, MPN};
